In [1]:
# import sys

# PATH_TO_WORKSPACE = '/Users/hassan/Documents/wod-prediction/WOD-prediction'
# sys.path.append(PATH_TO_WORKSPACE)

from pipeline_objects.data_loader import DataLoader
from pipeline_objects.preprocessor import DataPreprocessor
from pipeline_objects.modeling import RandomForestModel

In [ ]:
# loader = DataLoader(root_path = f'{PATH_TO_WORKSPACE}/Data',objects= ['open_results','descriptions','benchmark_stats'])
loader = DataLoader(root_path = f'../Data',objects= ['open_results','descriptions','benchmark_stats'])
data = loader.load()
data["benchmark_stats"].head()

/Users/JawanHaider/Documents/Projects/Collaborative/WOD-prediction/pipeline_objects/data_loader.py:48: DtypeWarning: Columns (2,3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(self.root_path, file))
/Users/JawanHaider/Documents/Projects/Collaborative/WOD-prediction/pipeline_objects/data_loader.py:48: DtypeWarning: Columns (2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(self.root_path, file))

,name,Back Squat,Chad1000x,Clean and Jerk,Deadlift,Fight Gone Bad,Filthy 50,Fran,Grace,Helen,L1 Benchmark,Max Pull-ups,Run 5k,Snatch,Sprint 400m
id,,,,,,,,,,,,,,,
469656,Jeffrey Adler,475.0,NaN,377.0,567.0,NaN,917.0,122.0,76.0,438.0,NaN,54.0,1155.0,290.0,59.0
300638,Tola Morakinyo,500.0,NaN,390.0,615.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,340.0,NaN
676693,Colten Mertens,555.0,NaN,335.0,545.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275.0,NaN
663689,Tyler Christophel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031875,Roldan Goldbaum,445.0,NaN,350.0,515.0,NaN,NaN,130.0,67.0,NaN,NaN,NaN,1080.0,280.0,56.0

In [ ]:
# to test the pipeline faster, we can sample the data, remove this line to use all the data
data['open_results'] = data['open_results'].sample(10000)
# Print the data to see what we have
data['open_results'].head()

,23.1,23.2A,23.2B,23.3,19.1,19.2,19.3,19.4,19.5,22.1,...,22.3,20.1,20.2,20.3,20.4,20.5,21.1,21.2,21.3,21.4
id,,,,,,,,,,,,,,,,,,,,,
105191,180 reps - s,106 reps - s,200 lbs - s,128 reps - s,NaN,101 reps,91 reps,66 reps,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1176459,NaN,NaN,NaN,NaN,285 reps,167 reps,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1577867,NaN,NaN,NaN,NaN,NaN,75 reps,NaN,72 reps - s,87 reps - s,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706816,NaN,NaN,NaN,NaN,229 reps,104 reps,98 reps,83 reps,128 reps,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1174117,NaN,NaN,NaN,NaN,261 reps,167 reps,96 reps,67 reps,138 reps,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
preprocessing_config = {
    'open_results':
    {
        'create_description_embeddings' : False,
    },
    # 'workout_descriptions':{},
    'benchmark_stats':{
        'remove_outliers': True,
        'missing_method':'zero'
    },
    # 'athlete_info':{}
}
preprocessor = DataPreprocessor(config=preprocessing_config)
preprocessed_data = preprocessor.transform(data=data)

In [ ]:
rf_modeler = RandomForestModel(n_estimators = 100)
rf_modeler.fit(**preprocessed_data)

rf_modeler.show_results()